import type { Metadata } from 'next'
import { NextIntlClientProvider } from 'next-intl'
import { getLocale } from 'next-intl/server'
import { Roboto } from 'next/font/google'
import Head from 'next/head'
import Script from 'next/script'
import { Layout } from '~/components/layout'
import { Providers } from '~/providers'
import { cn } from '~/utils/cn'
import './globals.css'

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['cyrillic']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const locale = await getLocale()

  return (
    <html lang={locale}>
      <Head>
        <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no' />
      </Head>
      <body className={cn(roboto.variable, 'antialiased')}>
        <NextIntlClientProvider>
          <Providers>
            <Layout>{children}</Layout>
          </Providers>
        </NextIntlClientProvider>
        <Script src='https://telegram.org/js/telegram-web-app.js' strategy='beforeInteractive' />
      </body>
    </html>
  )
}
