import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import Head from 'next/head'
import { Layout } from '~/components/layout'
import { Providers } from '~/providers'
import { cn } from '~/utils/cn'
import './globals.css'

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['cyrillic']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <Head>
        <meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no' />
      </Head>
      <body className={cn(roboto.variable, 'antialiased')}>
        <Providers>
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  )
}
